### PR TITLE
New draft accesskey rule

### PR DESCRIPTION
**Pull request by WilcoFiers**
Based on the work in issue #43.

### CODE REVIEW

**Comment by EmmaJP** [comment]
The rule is about the uniqueness of the accesskey values in a page, rather than whether or not they are sensible values.

**Comment by WilcoFiers** [comment]
We need to add tests to this as well.

**Comment by WilcoFiers** [comment]
@gianwild Merging this into draft, we'll open an issue to discuss your comment.

**Comment by EmmaJP** [comment]
https://github.com/auto-wcag/auto-wcag/issues/58

**Comment by gianwild** [comment]
I think we should make sure that people use this only for web applications, not standard web sites. It's a bit like role=menu - only makes sense on a complex web app not a standard web site.
And I always thought accesskeys were ALT + a character - not CTRL. Has that changed?

**Comment by EmmaJP** [comment]
@gianwild I think it's OK for either, as this rule about the uniqueness of the attribute value rather than how suitably it has been applied. That would be a different test, if there is need for one.

**Comment by gianwild** [comment]
Thanks @EmmaJP

**Pull request merged**
