### PR TITLE
chore: add html-validator for testing code snippets

### PR DESCRIPTION
**Pull request by jeeyyy**
> Note: This was attempted using `html-hint` in this PR.

I came across [html-validator](https://www.npmjs.com/package/html-validator) which uses `validator.w3.org/nu` for validating code fragments. This PR integrates a test which shows all testcases being validated using the above and which fail/ pass.

I have not fixed the failing testcases as I wanted to get more opinion on if this is the right way to go about solving for validity of testcases. Please see output https://circleci.com/gh/act-rules/act-rules.github.io/2715 for failed testcases.

If I get a thumbs up that this is the step in the right direction. I am happy to fix the failing testcase code snippets.

Closes issue(s): 
- https://github.com/act-rules/act-rules.github.io/issues/679

----

### **When creating PR:**
- Make sure you requesting to **pull a branch** (right side) to the `develop` branch (left side).

### **After creating PR:**
- Add yourself (and co-authors) as "Assignees" for PR.
- Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- Close the issue that the PR resolves (and make sure the issue is referenced in the top of this comment)
- Optionally request feedback from anyone in particular by assigning them as "Reviewers".

## How to Review And Approve
- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines. 
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.

### CODE REVIEW

**Comment by Jym77** [comment]
I think this looks nice, and the error messages of htmlvalidator are pretty good too.

👍

**Comment by EmmaJP** [comment]
I definitely think we should be providing valid HTML code in test cases. Otherwise the permutations become too many to reasonably cover.

**Comment by jkodu** [comment]
Cheers for the +1's. I will go ahead with the fixes.

**Review by carlosapaduarte — APPROVED** [review]

**Comment by Jym77** [comment]
One issue I see with validating everything it that some examples need to become way bigger to be valid HTML, typically the ones that are supposed to be full documents (for rules whose applicability is the full document).

Typically, I want to have an example for using `main` landmarks, like this:
```html
<html>
  <div role="main" aria-label="Translation by C. H. Brewitt-Taylor">
    The empire, long divided, must unite; long united, must divide. Thus it has ever been.
  </div>
  <div role="main" aria-label="Translation by Yu Sumei">
    Unity succeeds division and division follows unity. One is bound to be replaced by the other after a long span of time.
  </div>
</html>
```

But if I want this to be validated by [HTML validator](https://validator.w3.org/nu), it needs to be:
```html
<!DOCTYPE html>
<html lang="en">
  <head><title>Comparing translations of the Romance of the Three Kingdoms</title></head>
  <div role="main" aria-label="Translation by C. H. Brewitt-Taylor">
    The empire, long divided, must unite; long united, must divide. Thus it has ever been.
  </div>
  <div role="main" aria-label="Translation by Yu Sumei">
    Unity succeeds division and division follows unity. One is bound to be replaced by the other after a long span of time.
  </div>
</html>
```

which adds a lot of "useless" stuff not related to the example. This both takes up space to read (and time to write) and dilute the purpose of the example (less focused, harder to find out the parts actually relevant for the rule).

(this may be better be validating snippets, typically the `DOCTYPE` is probably not needed)

But then, I say we can always try and evaluate :-D

**Comment by jkodu** [comment]
Closing this PR, as discussed with @WilcoFiers that `html-hint` is a better solution.
So will be opening a similar PR like this - https://github.com/act-rules/act-rules.github.io/pull/631/files

**Pull request closed without merging**
