### PR TITLE
Dependencies updates

### PR DESCRIPTION
**Pull request by Jym77**
Replace `jest-expect-message` by `jest-27-expect-message` since the former breaks with Jest 27 and is not maintained anymore.
https://github.com/mattphillips/jest-expect-message/pull/40

Closes issue(s):

N/A

Need for Call for Review:
This can be merged with 1 approval (fixing test code)

---

### **When creating PR:**

- [X] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [X] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [X] Add yourself (and co-authors) as "Assignees" for PR.
- [X] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [ ] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [X] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

### CODE REVIEW

**Review by carlosapaduarte — DISMISSED** [review]
I'm unable to build with the updated version of remark-parse :-(

**Comment by Jym77** [comment]
@carlosapaduarte Kept `remark-parse` to non-breaking version 😕 
Also updated actions dependencies and `node` version.

**Review by carlosapaduarte — COMMENTED** [review]
@Jym77 Are you sure you want to include the changes to the workflow flows in this PR?

**Comment by Jym77** [comment]
> @Jym77 Are you sure you want to include the changes to the workflow flows in this PR?

Feel like they are also dependencies updates (of github actions and node) 🤷 
(and the tests do pass with the new workflows…)

**Review by carlosapaduarte — APPROVED** [review]

**Review by WilcoFiers — APPROVED** [review]

**Review by tbostic32 — APPROVED** [review]

**Pull request merged**
