### PR TITLE
meta refresh (no exceptions) examples should not fail SC 2.2.1

### PR DESCRIPTION
**Pull request by WilcoFiers**
/me Chair hat off, product owner hat on

I'm having difficulties mapping to the Meta element refresh (no exceptions) ACT rule. Axe-core has two rules on meta elements. One that tests for failures of SC 2.2.1, and one that tests for failures of SC 2.2.4 that are not failures of SC 2.2.1. I.e. two axe-core rules combined cover all of this single ACT rule.

The problem is that this "no exceptions" ACT rule has examples that also fail SC 2.2.1. When axe-core reports those as failures of both SC 2.2.1 and 2.2.4, that implementation ends up as partially consistent, because SC 2.2.1 isn't listed in the accessibility requirements.

I think there are two solutions for it:
1. Ensure the failed examples don't fail SC 2.2.1; or
2. Add SC 2.2.1 as a secondary requirement

I noticed we don't have this problem on color contrast (enhanced) because all its failed examples pass level AA. As a quick solve, I think this will work.

We'll need a broader conversation about which option we'll want for scenarios like this, as part of discussing secondary requirements. My guess is we'll end up with option 2, but I don't think we're ready to commit to that just yet, and I since this is a priority issue, I don't think we should wait.

Need for Call for Review: 1 week

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

### CODE REVIEW

**Comment by carlosapaduarte** [comment]
@WilcoFiers Wouldn't a solution similar to what was done in #1920 work for this rule also?

**Comment by WilcoFiers** [comment]
@carlosapaduarte It's not the same. On PR 1920 I set some requirements as secondary. Here the problem is that the SC that is getting failed isn't listed as an accessibility requirement. It's not allowed to be by the rules format, since SC 2.2.1 isn't always failed when this rule is failed.

This is the only way I think this can be solved under ACT Rules Format 1.0. Once we have an editors draft of 1.1, we'll have other options, but since this problem is hindering an implementation, and there is a way around the issue, I don't think we should wait.

**Review by HelenBurge — APPROVED** [review]

**Review by Jym77 — DISMISSED** [review]
Can you add a background note that refresh below 20h are also bad but not in the examples due to mappings?
Maybe also adding the other rule in the bibliography.

**Comment by WilcoFiers** [comment]
@Jym77 That feels inconsistent with what we did for Text has enhanced contrast. I think I'd rather keep them consistent TBH.

**Review by Jym77 — APPROVED** [review]

**Review by colabottles — APPROVED** [review]

**Review by tombrunet — APPROVED** [review]

**Pull request merged**
