### PR TITLE
Sc4 1 1 updates

### PR DESCRIPTION
**Pull request by WilcoFiers**

### CODE REVIEW

**Comment by EmmaJP** [comment]
Agreed to create a new pull request with only template changes, and then suggested adjustments as a second pull request.

**Comment by EmmaJP** [comment]
I was asked to split this into two separate pull requests - one moving to revised rule format with no other changes, and a second with other suggested changes. I think this pull request can be rejected.

**Comment by EmmaJP** [comment]
Impact from https://github.com/auto-wcag/auto-wcag/pull/31 and https://github.com/auto-wcag/auto-wcag/pull/32/files

**Comment by WilcoFiers** [comment]
Has been superseded by #53, #54, #55

**Pull request closed without merging**
