### PR TITLE
[b33eff]: CSS to put text on screen when rotated

### LINKED ISSUE #1782: "Orientation of the page is not restricted using CSS transform property" [b33eff]: Failed example 3 doesn't show on screen
When looking at [Failed example 3](https://act-rules.github.io/testcases/b33eff/a3781bdaef2c50a9a60b2c9ab749418be195017b.html) of rule [Orientation of the page is not restricted using CSS transform property](b33eff), in landscape mode on a wide screen, the page looks empty.
This is likely due to the wide `body` element being rotated on its rightmost corners and thus the small text on the left side got pushed off-screen at the top.

We should likely make sure there actually is something visible on both orientations.
(other examples of this rule might suffer from similar problems on either orientation, I haven't double checked all of them).

Screenshot of Failed Example 3, showing the rotated body element with its beginning pushed off-screen

### PR DESCRIPTION
**Pull request by tombrunet**
Adjusts the CSS so that the content is "visible" to avoid voiding the applicability of the rule.

Closes issue(s):

- closes #1782

Need for Call for Review:

This will require a 1 week Call for Review 

---

### **When creating PR:**

- [x] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [x] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [x] Add yourself (and co-authors) as "Assignees" for PR.
- [x] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [x] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [x] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [x] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

### CODE REVIEW

**Review by WilcoFiers — DISMISSED** [review]
This works, although I also seem to have issues with failed example 1 and 4. We should probably solve those as well.

**Review by Jym77 — APPROVED** [review]
I haven't checked all the other examples, but this is improving the situation on these two.

**Comment by tombrunet** [comment]
@WilcoFiers Fixed fail 1 and fail 4.

**Review by WilcoFiers — APPROVED** [review]
LGTM

**Review by carlosapaduarte — APPROVED** [review]

**Comment by Jym77** [comment]
Call for Review ends on December 14th.

**Review by 0066135 — APPROVED** [review]

**Comment by Jym77** [comment]
Cal for Review has ended. Merging.

**Comment by AndyAtTV** [comment]
Inapplicable Example 3 appears to have two mistakes: **landscape** is misspelled as **lanscape**, and **rotateZ()** should only have 1 argument, not 4 (maybe it should be **rotate3d** ?)

**Pull request merged**
