### PR TITLE
Form field name passed example should actually pass

### PR DESCRIPTION
**Pull request by WilcoFiers**
Labels with aria-hidden do **not** provide an accessible name. So passed example 8 was actually a failure. Using aria-labelledby does work because it specifically does allow hidden labels.

Need for Call for Review: **NONE** Please note, normally we do send this for review but I think this is a simple mistake, and we need it fixed before this goes to AGWG next week.

---

### **When creating PR:**

- [ ] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [ ] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [ ] Add yourself (and co-authors) as "Assignees" for PR.
- [ ] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [ ] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [ ] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

### CODE REVIEW

**Comment by giacomo-petri** [comment]
Thank you @WilcoFiers .

in your edit, I suggest to replace in passing example description the `label` with the WCAG 2.1 label definition. Right now the accessible name is provided by the relationship given by the aria-labelledby and not by the `<label>` itself.

**Review by ajanec01 — APPROVED** [review]

**Comment by WilcoFiers** [comment]
@giacomo-petri Can you put in a suggestion? I'm not sure what element you'd like to see it changed to. Personally I think label is most appropriate here, even using aria-labelledby, but I don't mind using something else. Not a big deal.

**Comment by giacomo-petri** [comment]
> @giacomo-petri Can you put in a suggestion? I'm not sure what element you'd like to see it changed to. Personally I think label is most appropriate here, even using aria-labelledby, but I don't mind using something else. Not a big deal.

I don't know why but I cannot put suggestions for the specific line of code.
I would suggest to change

> These `menuitemcheckbox` elements have an [accessible name][] given by their associated `label`.

with 

> These `menuitemcheckbox` elements have an [accessible name][] because of its aria-labelledby attribute.

only to emphasize that the accessible name is not given by the "natural" relationship between input and labels (such as using for and id, or wrapping the input inside its label), but is given by the aria-labelledby attribute that is pointing to the label element.

**Review by tombrunet — APPROVED** [review]

**Comment by WilcoFiers** [comment]
Aaahhh. I see. Agreed, yes. Will fix.

**Review by Jym77 — DISMISSED** [review]
* I second updating the description of the test to not include the `label` element.
* I also think we should maybe use another element than `label` to make thinks clearer. A `label` referenced to using an `aria-labelledby` (rather than `for`) sounds super wonky and I foresee it creating questions and misunderstanding (at best). This may be tackled later, though.
* Technically, hidden `label` should be used, but UA don't do it 🙈 I've gathered some ARIA discussion in [the related Alfa Issue](https://github.com/Siteimprove/alfa/issues/1266)… We might want an Accessibility Support note here (again, may be delayed to later).

**Review by giacomo-petri — APPROVED** [review]

**Review by Jym77 — APPROVED** [review]

**Pull request merged**
